import { PrismaClient } from "@prisma/client";

const prisma = new PrismaClient();

async function main() {
  // Seeding Order Data
  await prisma.order.createMany({
    data: [
      {
        SrNo: 1,
        orderNo: 71220250301, // Unique orderNo
        weight: 50,
        quantity: 100,
        orderDeliveryDate: new Date("2025-04-15"),
        grade: "A",
        thickness: 15,
        width: 250,
        orderThickness: 12,
        orderWidth: 230,
        tdc: "TDC111",
        deliveryPlace: "Mumbai",
        customerName: "John Doe",
        shippedBy: "BlueDart",
        createdBy: "Admin1",
        producedQuantityWeight: 500,
        producedQuantityNumber: 20,
        balanceWeight: 100,
        balanceNumber: 5,
        leastProductionDate: new Date("2025-03-10"),
        timeToShip: 4,
        timeForQualityCheck: 2,
      },
      {
        SrNo: 2,
        orderNo: 71220250302, // Unique orderNo
        weight: 40,
        quantity: 80,
        orderDeliveryDate: new Date("2025-04-20"),
        grade: "B",
        thickness: 18,
        width: 270,
        orderThickness: 15,
        orderWidth: 250,
        tdc: "TDC222",
        deliveryPlace: "Chennai",
        customerName: "Jane Smith",
        shippedBy: "DHL",
        createdBy: "Admin2",
        producedQuantityWeight: 600,
        producedQuantityNumber: 30,
        balanceWeight: 200,
        balanceNumber: 10,
        leastProductionDate: new Date("2025-03-15"),
        timeToShip: 3,
        timeForQualityCheck: 1,
      },
      {
        SrNo: 3,
        orderNo: 71220250303, // Unique orderNo
        weight: 60,
        quantity: 120,
        orderDeliveryDate: new Date("2025-04-25"),
        grade: "C",
        thickness: 20,
        width: 300,
        orderThickness: 18,
        orderWidth: 280,
        tdc: "TDC333",
        deliveryPlace: "Delhi",
        customerName: "Michael Johnson",
        shippedBy: "FedEx",
        createdBy: "Admin3",
        producedQuantityWeight: 700,
        producedQuantityNumber: 40,
        balanceWeight: 300,
        balanceNumber: 15,
        leastProductionDate: new Date("2025-03-20"),
        timeToShip: 5,
        timeForQualityCheck: 2,
      },
      {
        SrNo: 4,
        orderNo: 71220250304, // New unique orderNo
        weight: 30,
        quantity: 25,
        orderDeliveryDate: new Date("2025-04-30"),
        grade: "C",
        thickness: 12,
        width: 220,
        orderThickness: 10,
        orderWidth: 200,
        tdc: "TDC234",
        deliveryPlace: "Pune",
        customerName: "Alice Brown",
        shippedBy: "DHL",
        createdBy: "Admin4",
        producedQuantityWeight: 400,
        producedQuantityNumber: 16,
        balanceWeight: 200,
        balanceNumber: 9,
        leastProductionDate: new Date("2025-03-30"),
        timeToShip: 3,
        timeForQualityCheck: 1,
      },
      {
        SrNo: 5,
        orderNo: 71220250305, // New unique orderNo
        weight: 20,
        quantity: 40,
        orderDeliveryDate: new Date("2025-05-05"),
        grade: "B",
        thickness: 14,
        width: 260,
        orderThickness: 12,
        orderWidth: 240,
        tdc: "TDC567",
        deliveryPlace: "Hyderabad",
        customerName: "Robert Wilson",
        shippedBy: "FedEx",
        createdBy: "Admin5",
        producedQuantityWeight: 600,
        producedQuantityNumber: 30,
        balanceWeight: 200,
        balanceNumber: 10,
        leastProductionDate: new Date("2025-04-01"),
        timeToShip: 4,
        timeForQualityCheck: 2,
      },
      {
        SrNo: 6,
        orderNo: 71220250306, // New unique orderNo
        weight: 30,
        quantity: 60,
        orderDeliveryDate: new Date("2025-05-10"),
        grade: "A",
        thickness: 22,
        width: 320,
        orderThickness: 20,
        orderWidth: 300,
        tdc: "TDC890",
        deliveryPlace: "Bangalore",
        customerName: "Sophia Davis",
        shippedBy: "BlueDart",
        createdBy: "Admin6",
        producedQuantityWeight: 800,
        producedQuantityNumber: 50,
        balanceWeight: 200,
        balanceNumber: 10,
        leastProductionDate: new Date("2025-04-05"),
        timeToShip: 5,
        timeForQualityCheck: 3,
      },
    ],
  });
  

  await prisma.inventory.createMany({
    data: [
      {
        IN_MaterialName: "IN20250301",
        IN_Thickness: 2.5,
        IN_Width: 1200.5,
        IN_Weight: 500.0,
        IN_Grade: "A36",
        ActuallWeight: 490.5,
        In_ProductionDate: new Date("2024-03-10T00:00:00.000Z"),
        YardArrivalDate: new Date("2024-03-15T00:00:00.000Z"),
        Residence_INYard: "Section A",
        YardNO: "Y-101",
        Position: "Row 5, Shelf 3",
        Manufacturing_Location: "Plant 1",
        Manufacturer: "SteelCorp Ltd.",
      },
      {
        IN_MaterialName: "IN20250302",
        IN_Thickness: 3.0,
        IN_Width: 1300.0,
        IN_Weight: 600.0,
        IN_Grade: "B500",
        ActuallWeight: 595.0,
        In_ProductionDate: new Date("2024-03-12T00:00:00.000Z"),
        YardArrivalDate: new Date("2024-03-18T00:00:00.000Z"),
        Residence_INYard: "Section B",
        YardNO: "Y-102",
        Position: "Row 2, Shelf 1",
        Manufacturing_Location: "Plant 2",
        Manufacturer: "MetalWorks Pvt. Ltd.",
      },
      {
        IN_MaterialName: "IN20250303",
        IN_Thickness: 4.5,
        IN_Width: 1100.8,
        IN_Weight: 750.0,
        IN_Grade: "C45",
        ActuallWeight: 745.5,
        In_ProductionDate: new Date("2024-03-14T00:00:00.000Z"),
        YardArrivalDate: new Date("2024-03-20T00:00:00.000Z"),
        Residence_INYard: "Section C",
        YardNO: "Y-103",
        Position: "Row 4, Shelf 2",
        Manufacturing_Location: "Plant 3",
        Manufacturer: "IronTech Industries",
      },
    ],
  });

  console.log("✅ Order and Inventory data seeded successfully");
}


main()
  .catch((e) => console.error(e))
  .finally(async () => {
    await prisma.$disconnect();
  });
